### ISSUE TITLE
[HIGH] Actual RSVP# does not match set RSVP Limit

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#46] opened 2021-01-19 20:28 UTC
Many times the number of RSVPs the event page accepts is less than the set Limit RSVP number.
This has been an on & off issue for a while but didn't affect us enough to be brought up. It affects us now, though, since we are reaching capacity for our sessions! It is too much for me to track each event to make sure these RSVP limits match the actual RSVP #.
For example:
- [This event](https://sdrefugeetutoring.com/event/elem-tutoring-2021-01-21/) was made with Limit RSVPs = 47. 
- There are only 40 people RSVP'd on the event page, but the event page says "We currently need 5 more tutors." Which is only 45, not 47.
- So I had to Edit the event to increase the Limit RSVP to "49" in order to have the RSVPs cap out at the correct number of 47.

**Comment by JasonTheAdams** [comment] 2021-04-25 00:33
Hi @dreazee!

Off by 2. Hmm. I took a stab at this and, while I couldn't reproduce the issue, I could see some improvements in the code to avoid some weird computations from happening. So it may be fixed.

If the problem persists, keep in mind that for an RSVP to count against the limit, it must meet two criteria:
- The volunteer provided a name
- The RSVP itself is published (it can't be a draft or in the trash)

I'm going to close this, as it's possibly fixed, but we can re-open this if it pops up again. 😃

**Closed as completed by JasonTheAdams** 2021-04-25 00:33 UTC

**Comment by dreazee** [comment] 2021-04-26 17:27
Thanks @JasonTheAdams! While it was an ongoing issue previously, I actually haven't seen this issue recently. Will definitely reopen this case if it pops up again.
