### ISSUE TITLE
[VERY HIGH] Expand Requirements in order to allow a User to RSVP to "protected" events

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#41] opened 2020-08-20 21:32 UTC
To reiterate, a User would only be able to RSVP when 4 requirements are completed:
1. Background Check (ideally to be automatically updated in User Profile)
2. Orientation Attendance (Manually updated in User Profile under "Volunteer Profile Info")
3. Code of Conduct digitally signed online (auto update in User Profile)
4. Volunter Release digitally signed (auto update in User Profile)

Right now, a User only needs to complete a Background Check in order for them to be able to RSVP - as Role changes from "Volunteer Pending" to "Volunteer".

**Comment by mathetos** [comment] 2020-08-22 23:54
Fixed via https://github.com/SDRefugeeTutoring/sdrt-custom-functions/commit/e235769b0ce6fd2e964e729a7f052a7cc1dc59f8

**Comment by dreazee** [comment] 2021-09-15 23:07
@JasonTheAdams Per my earlier email, this is the EXACT issue we are having again.

**Comment by JasonTheAdams** [comment] 2021-09-16 04:01
I've re-opened this issue as we look into this. Here's what I've found so far:

I can see where a user is required to have all four conditions in order for a volunteer to RSVP. These conditions, however, are too forgiving and easily bypassed as a fluke. I updated the conditions (b372d05) to make them more strict.

I also saw that the "Must Users be Logged In?" (see below) must be set to "Yes" in order for the capability check to work. If it's "No", then anyone can RSVP. I noticed that the "Sept. 16 New Tutor Virtual Orientation & Training" event was set to "No". I'm not sure if this is by design or a bug. @dreazee, can you please let me know if this is intended behavior?

![Image 2021-09-15 at 8 59 31 PM](https://user-images.githubusercontent.com/2024145/133547327-191f17e8-26a3-47bc-8f08-f27450010762.jpg)

**Comment by dreazee** [comment] 2021-09-16 17:16
@JasonTheAdams  Yes, this is intended behaviour. For New Tutor Orientations (NTOs), a user does not need to be logged in since they do not need to be registered to join. NTOs use an Orientation Form, though, where name/email is entered. An RSVP form is the form that is used when "Must Users be Logged In' is set to "Yes". This "protected" RSVP form is the one that is used for Tutoring Dates and Returning Tutor Refreshers.

**Comment by JasonTheAdams** [comment] 2021-09-17 01:18
Got it! Thanks for explaining that! I'll go ahead and close this, then, since it sounds like it's working. 👍

**Closed as completed by JasonTheAdams** 2021-09-17 01:18 UTC
