### ISSUE TITLE
[HIGH!] Change "Welcome" Email for Newsletter Subscribers

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#45] opened 2021-01-19 19:59 UTC
The Email people receive after signing up to the newsletter is a bit... confusing. It seems to be the same form used after submitting a question on the website? That would be great to change this! Please see screenshot below for details. 
![Screenshot (3)](https://user-images.githubusercontent.com/47679296/105086271-aa3c6b00-5a4d-11eb-8a20-80f0f512e26b.png)

**Comment by dreazee** [comment] 2021-01-19 20:16
Looks like I had already submitted this back in July! #37

**Comment by JasonTheAdams** [comment] 2021-10-29 02:02
Closing this as a duplicate of #37

**Closed as completed by JasonTheAdams** 2021-10-29 02:02 UTC
